
## Init
FROM php:5.6.30-apache
WORKDIR /var/www/html

## Extends PHP
RUN apt-get update && apt-get install -y libc6-i386
RUN apt-get update && apt-get install -y libc-client-dev libkrb5-dev
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl
RUN docker-php-ext-install imap
RUN docker-php-ext-install mysql
RUN docker-php-ext-install mysqli
RUN apt-get update && apt-get install -y zlib1g-dev
RUN docker-php-ext-install zip
RUN docker-php-ext-install pdo pdo_mysql
RUN apt-get update && apt-get install -y php5-intl
RUN find /usr/lib/php5/ -name intl.so -exec mv -t "$(php -r 'echo ini_get("extension_dir");')" {} +
RUN echo "extension=intl.so" >> /usr/local/etc/php/conf.d/custom.ini
#COPY php.ini /usr/local/etc/php/php.ini

## Extends Apache
RUN usermod -u 1000 www-data

## Command-line utils
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer --quiet && \
    rm composer-setup.php

## Install command
COPY install /usr/local/bin/install
RUN chmod +x /usr/local/bin/install

## Install command
COPY update /usr/local/bin/update
RUN chmod +x /usr/local/bin/update

## Build command
COPY build /usr/local/bin/build
RUN chmod +x /usr/local/bin/build

## Test command
COPY test /usr/local/bin/test
RUN chmod +x /usr/local/bin/test

## TDD command
COPY tdd /usr/local/bin/tdd
RUN chmod +x /usr/local/bin/tdd

## Info command
COPY info /usr/local/bin/info
RUN chmod +x /usr/local/bin/info

## Create operation user
RUN useradd -ms /bin/bash -g www-data phpython

## Cleanup
RUN apt-get clean && rm -rf /tmp/* /var/tmp/* && rm -rf /var/lib/apt/lists/*

## Define default command
CMD ["apachectl", "-D", "FOREGROUND"]