
FROM php:5.6.30-apache
WORKDIR /

RUN apt-get update && apt-get install -y libc6-i386

##
COPY phpython-build.sh /usr/local/bin/build
RUN chmod +x /usr/local/bin/build

## Define default command
CMD ["apachectl", "-D", "FOREGROUND"]